
# This file is automatically generated during the generation of setup.py
# Copyright 2020, Caer
author = 'Jason Dsouza <jasmcaus@gmail.com>'
version = '0.0.2'
full_version = '0.0.2'
release = True
contributors = ['Jason Dsouza <jasmcaus@gmail.com>']
